### PR TITLE
Updated to 1.14.1

### PR DESCRIPTION
**Pull request by Shnupbups**
Updated the Fabric port to 1.14.1

### CODE REVIEW

**Comment by McJty** [comment]
Thanks a lot! But what are the extras?

**Comment by Shnupbups** [comment]
I updated the fabric.mod.json to the new schema and combined the mixin jsons into one, both of which aren't *required*, but recommended. I also changed the English localisation to the new json format, and added a note to the localisation for the protection wand that it crashes the game.

This is in addition to all the stuff necessary to get the mod working on 1.14.1.

**Comment by McJty** [comment]
Hmm. Is this incomplete? I merged this PR, updated locally, did gradlew genSources and I get lots of compile errors. For example these are imports that no longer exist:

import net.minecraft.ChatFormat;
import net.minecraft.client.item.TooltipContext;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.TextComponent;

So what's up?

**Comment by Shnupbups** [comment]
Those *do* exist, make sure to update your yarn mappings to 1.14.1+build.10.

**Comment by McJty** [comment]
Well I'm just using the build.gradle from your patch and did do genSources. So what else do I have to do?

**Comment by McJty** [comment]
Have been out of the loop with fabric for a while. Apparantly something more has changed

**Comment by Shnupbups** [comment]
Hmm, you shouldn't have to do any more than that... odd. Works on my machine.

**Comment by Shnupbups** [comment]
Try running `gradlew genSources` before you run `gradlew build`.

**Comment by McJty** [comment]
Well I didn't do gradlew build. I was building from IDEA
Anyway I'm trying genSources again. Perhaps something was not ok the first time (even though I did not get any errors)

**Comment by McJty** [comment]
Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve net.fabricmc.mapped:net.fabricmc.yarn.10.net.fabricmc.fabric-api.fabric-events-interaction-v0:0.1.0+59147463.
  Required by:
      project :
   > Could not resolve net.fabricmc.mapped:net.fabricmc.yarn.10.net.fabricmc.fabric-api.fabric-events-interaction-v0:0.1.0+59147463.
      > Could not get resource 'https://maven.fabricmc.net/net/fabricmc/mapped/net.fabricmc.yarn.10.net.fabricmc.fabric-api.fabric-events-interaction-v0/0.1.0+59147463/net.fabricmc.yarn.10.net.fabricmc.fabric-api.fabric-events-interaction-v0-0.1.0+59147463.jar'.
         > Could not HEAD 'https://maven.fabricmc.net/net/fabricmc/mapped/net.fabricmc.yarn.10.net.fabricmc.fabric-api.fabric-events-interaction-v0/0.1.0+59147463/net.fabricmc.yarn.10.net.fabricmc.fabric-api.fabric-events-interaction-v0-0.1.0+59147463.jar'.
            > Read timed out

**Comment by McJty** [comment]
That's what I get. Sorry for the formatting. Not sure how to do blockquotes here

**Comment by Shnupbups** [comment]
Odd. Build works perfectly fine for me (though I am using `gradlew build`)

I can give you the built jar if you'd like? I'm honestly not sure why it wouldn't be working.

**Comment by McJty** [comment]
That's fine. I'll figure it out here first. I want to get this working for myself too

**Comment by McJty** [comment]
Ok, now I get different problems:

C:\Personal\projects\Fabric\notenoughwands1.8.8\src\main\java\romelo333\notenoughwands\network\PacketReturnProtectedBlocksAroundPlayer.java:5: error: cannot find symbol
import net.minecraft.world.chunk.ChunkPos;
                                ^
  symbol:   class ChunkPos
  location: package net.minecraft.world.chunk
C:\Personal\projects\Fabric\notenoughwands1.8.8\src\main\java\romelo333\notenoughwands\network\PacketReturnProtectedBlocksAroundPlayer.java:13: error: cannot find symbol
    private Map<ChunkPos, Set<BlockPos>> blocks;
                ^
  symbol:   class ChunkPos
  location: class PacketReturnProtectedBlocksAroundPlayer
C:\Personal\projects\Fabric\notenoughwands1.8.8\src\main\java\romelo333\notenoughwands\network\PacketReturnProtectedBlocksAroundPlayer.java:46: error: cannot find symbol
    public Map<ChunkPos, Set<BlockPos>> getBlocks() {
               ^
  symbol:   class ChunkPos
  location: class PacketReturnProtectedBlocksAroundPlayer
C:\Personal\projects\Fabric\notenoughwands1.8.8\src\main\java\romelo333\notenoughwands\network\PacketReturnProtectedBlocksAroundPlayer.java:53: error: cannot find symbol
    public PacketReturnProtectedBlocksAroundPlayer(Map<ChunkPos, Set<BlockPos>> blocks) {
                                                       ^
  symbol:   class ChunkPos
  location: class PacketReturnProtectedBlocksAroundPlayer
Note: Writing refmap to C:\Personal\projects\Fabric\notenoughwands1.8.8\build\classes\java\main\notenoughwands1.8.8-refmap.json
Note: Writing refmap to C:\Personal\projects\Fabric\notenoughwands1.8.8\build\classes\java\main\notenoughwands1.8.8-refmap.json
Note: Writing named:intermediary output TinyMappings to C:\Personal\projects\Fabric\notenoughwands1.8.8\build\loom-cache\mixin-map-1.14.1-10.tiny
4 errors

**Comment by McJty** [comment]
Ok, gradlew build works now. Had some local changes that were invalid
But IDEA is still a problem

**Comment by McJty** [comment]
Ok, solved it by doing gradlew ideaGenWorkspace
All is ok now :-)

**Comment by McJty** [comment]
I don't know if you would feel like porting The One Probe as well? It's ok if you don't have time for that (or don't want to do it)

**Comment by Shnupbups** [comment]
Sure. I'm on the Fabric Discord if you'd prefer to talk there.

**Pull request merged**
