### PR TITLE
update to 1.18

### PR DESCRIPTION
**Pull request by remplerus**
- don't know if acceleration wand and protection wands work, other wands work as intended.
- added some todo's as idk if some functions work as intended

### CODE REVIEW

**Comment by McJty** [comment]
Thanks. I'll check it out soon!

**Comment by McJty** [comment]
Sorry, 'soon' is a relative term. Got a lot on my plate right now. I haven't forgotten though

**Comment by remplerus** [comment]
no worries, i just try to help updating useful mods to 1.18 if i can :)

**Comment by McJty** [comment]
I fixed the protection wand and acceleration wand. I also fixed the moving and displacement wands because they were not correctly moving tile entity data (i.e. chests became empty after moving)

To save a block entity you need to use 'saveWithoutMetadata'

**Pull request merged**
